### ISSUE TITLE
[FEATURE] - have an option to copy whole line if cursor is at the start/end of line

### ISSUE THREAD

**Issue by ctf0** [alefragnani/vscode-copy-word#20]
it would be very helpful too if we can fallback to the normal copy/cut if no selection was made.

**Comment by alefragnani** [comment]
Hi @ctf0 ,

Yep, that would be useful. Probably handle "start of the line" position as well.

Thanks for the suggestion

**Comment by dudeNumber4** [comment]
Hopefully I can get clarification because I don't know what is meant by "fallback to the normal copy/cut if no selection was made."  The whole reason I added this extension was to get the functionality exactly as it's named - to copy the current word without having to bother selecting it first.  Then, I added the MR to make it paste over the current word without having to select it first.
The other issue is copying the current line.  Most of the time, when programming, your words don't start at the left margin.  When your cursor is at the left margin, you're considering lines, not words.  Thus, the default behavior of copying the current line in this case makes sense.  That's what my current MR is for.
Do y'all agree?

**Comment by alefragnani** [comment]
The _fallback_, in this case, will mean _"use VS Code default behavior - copy the entire line - when the extension is not able to select a word".

If you remember, VS Code has `"editor.emptySelectionClipboard"` setting, with its default value as `true`. It means that if there is no selection, no matter where the cursor is (begin, end, empty space, any word), it will copy the entire line. The object of this extension is, if the cursor is positioned in any word, copy it, instead of the line.

The proposal for a _fallback_ is to respect this behavior **only if the extension can't select a word**. In other words, the result will be:

* Is the cursor at the start of the line (empty space / tab) -> copy the line
* Is the cursor at the end of the line (empty space / tab) -> copy the line
* Is the cursor at an empty space sequence (empty space / tab) -> copy the line

And the normal extension behavior
* Is the cursor positioned in any word/character sequence -> copy the word

**Comment by dudeNumber4** [comment]
Very good.  I had no idea the default behavior was to copy the line other than when the cursor was at the margin.  I'll adjust my MR accordingly.

**Comment by ctf0** [comment]
many thanks for the new feature, however, atm if u tried to paste something at the start of a word, this word will be replaced ex.
```
// original text
world

// | is the cursor
|world

// paste something
// current behavior
hello

// expected behavior
helloworld
```

**Comment by alefragnani** [comment]
Hi @ctf0 ,

The original/regular `Paste` command that comes with VS Code works as expected, pasting the content at the beginning of the word.

However, the new `Copy Word: Paste` command, created in #40, reproduces the behavior you described. Which as I understand is the _expected_ behavior of that issue. Pinging @dudeNumber4 to share its thoughts about the command created there.

BTW, I prefer using the original/regular `Paste` command, as my main issue with VS Code behavior (and the reason behind this extension) is about the `Copy` and `Cut` commands.

Hope this helps

**Comment by ctf0** [comment]
ah ok, thats why then, thanks for the clarification

**Comment by ctf0** [comment]
@dudeNumber4 have u tested with multi cursor ? is it working with u ?

**Comment by alefragnani** [comment]
@ctf0 just to remember/clarify, but this extension doesn't support multi-cursor.

I just tested with the setting `true` and`false` and it seems to _respect_ multi-cursor when `false`, as the regular/native `Copy` command does. And does not copy anything when `true`, as expected, because no word could be selected.

Hope this helps

**Comment by ctf0** [comment]
oh dam it, i thought it works as there no notes about the no multi cursor support, my bad.

**Comment by alefragnani** [comment]
No problem! Sometimes I forget that too.

Feel free to open a feature request. I could find some time for that in the future 😁
