### ISSUE TITLE
Doesn't work since the new version of VSCode (1.1.0)

### ISSUE THREAD

**Issue by zabel-xyz** [alefragnani/vscode-copy-word#3]
The word is selected, but the entire line is copied.

**Comment by alefragnani** [comment]
This problem was also happening before the March release of VSCode, and it was fixed in the _Insider_ release back in March. _(It was a VSCode issue)_ I guess something has changed and the problem returned.

I contacted the VSCode team to check the issue and hope to have something new soon.

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/6994

**Comment by alefragnani** [comment]
Since the recomentation is stop using the native commands `editor.action.clipboardCopyAction` and `editor.action.clipboardCutAction`, I updated to use the node package https://github.com/xavi-/node-copy-paste instead, as suggested.

I tested on Windows, but the package itself says to be compatible with Mac and Linux.
